import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";
export const metadata: Metadata = { title: "Política de Privacidad | CercaYa", description: "Qué datos utiliza CercaYa y cómo se cuida tu información." };
export default function PrivacyPage() {
  return <LegalPage title="Política de Privacidad" intro="CercaYa es responsable del uso de la información que compartís en la plataforma. Acá te contamos qué datos usamos y para qué.">
    <section><h2>1. Qué información usamos</h2><p>Podemos manejar tu nombre, email, teléfono, localidad, ubicación cuando la autorizás, dirección y referencias de entrega. También guardamos información de pedidos, reservas, pedidos abiertos, ofertas, comercios, productos y reportes, junto con los datos necesarios para el funcionamiento, la seguridad y la moderación de CercaYa.</p><p>Registramos la fecha en que aceptás los Términos y leés esta Política y, si creás un comercio, la aceptación de sus reglas. Las cuentas están destinadas a personas de 18 años o más. No pedimos fecha de nacimiento ni DNI para registrarte.</p></section>
    <section><h2>2. Para qué utilizamos tus datos</h2><p>Para crear y mantener tu cuenta, mostrar comercios y productos cercanos, gestionar pedidos y permitir retiro o entrega. También para facilitar el contacto entre comprador y comercio, brindar soporte y prevenir fraude, spam y otros usos indebidos.</p><p><strong>CercaYa no vende datos personales.</strong></p></section>
    <section><h2>3. Cuenta y acceso con Google</h2><p>Usamos tu nombre y email para identificar tu cuenta y gestionar el acceso. El email no se publica en el catálogo. Supabase proporciona la autenticación y la sesión.</p><p>Si iniciás sesión con Google, CercaYa recibe únicamente la información básica necesaria para autenticarte, como nombre, email e identificador de cuenta, según los permisos concedidos. No necesitamos acceso a tus correos, contactos ni archivos de Google.</p></section>
    <section><h2>4. Ubicación opcional</h2><p>Usamos tu ubicación para mostrarte productos y comercios cercanos y calcular distancias. Sólo accedemos a ella cuando elegís utilizarla y autorizás el permiso del navegador. Puede ser aproximada o precisa según el dispositivo y el permiso. La ubicación exacta del comprador no se publica públicamente.</p><p>La ubicación del catálogo se conserva en este navegador hasta que decidas quitarla. Geoapify puede recibir las coordenadas para resolver el nombre de la localidad. Si elegís incluir ubicación en un Pedido Abierto, se guarda de forma privada para calcular la distancia a los comercios; el Radar muestra distancia, sin entregar tus coordenadas.</p><p>Podés dejar de usar ubicación desde la aplicación o revocar el permiso del navegador. Quitar la ubicación del catálogo no modifica la que ya incluiste en un pedido publicado. No hacemos seguimiento continuo de tus movimientos.</p></section>
    <section><h2>5. Pedidos y datos de entrega</h2><p>Los pedidos guardan los productos, cantidades, precios, comercio, modalidad y estado necesarios para gestionarlos. Las ofertas y los pedidos abiertos conservan la información necesaria para que sus participantes puedan consultarlos y responder.</p><p>En un pedido con envío, nombre, teléfono, dirección, localidad y referencias pueden compartirse con el comercio correspondiente para preparar y realizar la entrega, según el estado del pedido. No son datos públicos. En retiro también se utilizan los datos de contacto necesarios para coordinar el pedido.</p><p>El personal autorizado de CercaYa puede consultar los datos necesarios para soporte, seguridad y moderación. Los reportes no se publican ni se muestran a otros usuarios comunes. Evitá escribir datos sensibles o direcciones privadas en descripciones públicas.</p></section>
    <section><h2>6. Información de comercios y productos</h2><p>El nombre, categorías, localidad, dirección comercial, WhatsApp, descripción, logo, portada y opciones de entrega que publica un comercio forman parte de su presentación pública. Los productos públicos muestran imágenes, descripción, precio y disponibilidad. Publicá únicamente información e imágenes que quieras compartir.</p><p>Los comercios son independientes y deben usar los datos del comprador sólo para gestionar su pedido. Si abrís WhatsApp, salís de CercaYa; el mensaje preparado sólo se envía cuando vos lo confirmás allí.</p></section>
    <section><h2>7. Pagos</h2><p>CercaYa no procesa ni recibe pagos en esta primera versión. El pago se coordina directamente entre comprador y comercio, mediante efectivo, transferencia o a coordinar, según las opciones que ofrezca cada comercio.</p></section>
    <section><h2>8. Proveedores y sesión</h2><p>Utilizamos proveedores tecnológicos para infraestructura, autenticación, almacenamiento y funcionamiento: Supabase, Vercel, Google cuando elegís ese acceso y Geoapify para obtener el nombre de la localidad. Reciben la información necesaria para prestar esos servicios.</p><p>Usamos cookies y mecanismos de sesión necesarios para autenticarte y mantener tu acceso. El navegador también conserva preferencias y datos locales de funcionamiento. No agregamos publicidad ni tracking con esta implementación. Podés administrar el almacenamiento desde el navegador; borrarlo puede cerrar tu sesión o quitar preferencias.</p></section>
    <section><h2>9. Tus datos y contacto</h2><p>Podés solicitar acceso, corrección, actualización o eliminación de tus datos cuando corresponda escribiendo a <a href="mailto:soporte@cercaya.com.ar">soporte@cercaya.com.ar</a>. Podemos necesitar verificar que la cuenta sea tuya; nunca te pediremos la contraseña.</p><p>Conservamos los datos mientras sean necesarios para el funcionamiento, gestionar operaciones y cumplir obligaciones aplicables. Una solicitud de eliminación puede requerir conservar información de pedidos o seguridad cuando corresponda.</p><p>Podemos actualizar esta política si cambia el funcionamiento de CercaYa. La versión vigente y su fecha estarán disponibles en esta página.</p></section>
  </LegalPage>;
}
