import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";
export const metadata: Metadata = { title: "Términos y Condiciones | CercaYa", description: "Reglas simples para usar CercaYa y coordinar pedidos con comercios locales." };
export default function TermsPage() {
  return <LegalPage title="Términos y Condiciones" intro="Estas reglas explican cómo funciona CercaYa en su primera etapa y qué esperamos de quienes utilizan la plataforma.">
    <section><h2>1. Qué es CercaYa</h2><p>CercaYa permite encontrar comercios locales, buscar productos, consultar disponibilidad, realizar pedidos y contactar comercios cercanos. Proporcionamos la plataforma y herramientas de soporte y moderación.</p><p>Los comercios son independientes. Cada comercio es responsable de los productos que publica, sus precios, disponibilidad, calidad, entrega, facturación, garantía y cumplimiento de sus obligaciones. CercaYa también mantiene las responsabilidades que le correspondan por el servicio que presta.</p></section>
    <section><h2>2. Tu cuenta</h2><p>Las cuentas están destinadas a personas de 18 años o más. Al registrarte declarás cumplir esa edad, aceptás estos Términos y confirmás haber leído la Política de Privacidad. Usá información verdadera y cuidá el acceso a tu cuenta. No compartas tu contraseña ni utilices la identidad de otra persona.</p></section>
    <section><h2>3. Disponibilidad y pedidos</h2><p>Podés realizar pedidos de uno o varios productos del mismo comercio. El comercio puede confirmar, preparar, entregar o disponer para retiro y completar el pedido mediante las herramientas disponibles.</p><p>La disponibilidad puede cambiar entre la búsqueda y la confirmación. Un producto con stock informado o disponible hoy puede dejar de estar disponible. Revisá los detalles, precios y opciones de entrega, y aguardá la confirmación del comercio.</p><p>Los pedidos abiertos permiten contar qué necesitás y recibir ofertas de comercios. Acordá los detalles necesarios con el comercio y respetá los pedidos que confirmás.</p></section>
    <section><h2>4. Pago y comisión</h2><p>CercaYa no procesa ni recibe pagos en esta primera versión. El pago se realiza directamente entre comprador y comercio, en efectivo, por transferencia o a coordinar según las opciones disponibles.</p><p>Durante esta etapa inicial CercaYa no cobra comisión por las operaciones. No te pediremos transferir dinero a CercaYa para concretar un pedido.</p></section>
    <section><h2>5. Uso permitido y moderación</h2><p>No se permite fraude, información falsa, productos ilegales, spam, abuso, pedidos falsos, suplantación de identidad ni otros usos indebidos de la plataforma.</p><p>CercaYa puede bloquear productos, suspender comercios o suspender usuarios cuando corresponda. Podés reportar productos o comercios desde sus páginas. Los reportes son revisados; enviar uno no bloquea automáticamente el recurso.</p></section>
    <section><h2>6. Problemas y contacto</h2><p>Para resolver cuestiones de calidad, entrega, facturación o garantía, contactá al comercio responsable. Si necesitás ayuda con la plataforma o querés informar un uso indebido, usá el <a href="/contacto">Formulario de contacto de CercaYa</a>.</p><p>Estos Términos no eliminan los derechos que te correspondan como consumidor. Podemos actualizar el texto cuando cambie el servicio; la versión vigente estará publicada acá.</p></section>
  </LegalPage>;
}
